### PR TITLE
Report job id if failure happens after submission

### LINKED ISSUE #54: Job id is not reported when job fails using Blocking mode

### PR DESCRIPTION
**Pull request by regadas**
Fixes #54

### CODE REVIEW

File: controllers/flinkcluster_submit_job_script.go [hunk 1]
```diff
@@ -35,7 +35,7 @@ var submitJobScript = `
 #	Printing result to stdout. Use --output to specify output path.
 #	Job has been submitted with JobID ec74209eb4e3db8ae72db00bd7a830aa
 #
-# When failed (no jobID):
+# When failed (no jobID if running detached mode):
```
Comment (regadas) [inline controllers/flinkcluster_submit_job_script.go:38]:
```suggestion
# When submission fails (no jobID):
```

**Review by jto — APPROVED** [review]
