### PR TITLE
job-cancel control should tear down the cluster within a reasonable amount of time

### LINKED ISSUE #434: Job cancel is buggy
Job-cancel command does not work as expected in some cases. 
Some cases observed:
- If an unavailable flink image is used, job submitter stays in a pending state, it stays stuck in pending state. This will lead to the submitter pod stuck in an unschedulable state. It leads to this dangerous situation that the cluster can not scale down because of one unschedulable pod.
- Job finished (succeeded), but cluster isn't torn down. JobManager and TaskManagers stay running.
- With pod disruption budget, these unhealthy should-be-killed-clusters can block some nodes from upgrading etc. too.

In case of job-cancel, we should just kill all pods within a reasonable amount of time.

### PR DESCRIPTION
**Pull request by live-wire**
Fixes #434 
+

- control status requested should only be updated at the first reconcile (and not every reconcile). To keep track of when the control was actually requested.
- Reasonable amount of time can then be computed from when the control was requested.

### CODE REVIEW

File: apis/flinkcluster/v1beta1/flinkcluster_default.go [hunk 1]
```diff
@@ -27,6 +29,7 @@ import (
 const (
 	DefaultJobManagerReplicas  = 1
 	DefaultTaskManagerReplicas = 3
+	ForceTearDownAfter         = time.Second * 10
```
Comment (live-wire) [inline apis/flinkcluster/v1beta1/flinkcluster_default.go:32]: This could be configured to slightly higher if necessary

**Review by regadas — CHANGES_REQUESTED** [review]
Hi @live-wire! Well I don't particularly fancy this solution tbh. The issues mentioned in #434 might actually be valid and I think from a first look that it's possible and worth tackling them differently.

I don't have time now but I can later today (next week) give more details / chat about this.

**Comment by live-wire** [comment]
@regadas Sure. Let's sync on ways around it next week 👍

**Comment by live-wire** [comment]
Hey @regadas 👋 
How do you want to go about it ? :)

**Review by kassybas — APPROVED** [review]
We can certainly improve and refactor based on the feedback from @regadas, however since this is often causes pods to be pending and not cancel, i think we should go ahead and merge.

**Comment by live-wire** [comment]
Thanks @kassybas.
I agree. Merging this for now. 
I'll keep the original ticket open then. Please add the suggestions there @regadas 🙏
